service: studentit-mapit

plugins:
  - serverless-secrets-plugin
  - serverless-wsgi

provider:
  name: aws
  runtime: python3.6
  region: ap-southeast-2
  memorySize: 128
  timeout: 30
  stackTags:
    Purpose: StudentIT
    Environment: ${self:custom.stage}

package:
  exclude:
    - '**' # everything
  include:
    - '*.py'
    - 'mapit/**/*.py'
    - '.requirements/**' # Serverless WSGI
    - '.wsgi_app' # Serverless WSGI

functions:
  mapit:
    handler: wsgi.handler
    environment: ${file(secrets.${self:custom.stage}.yml)}
    events:
      - http: ANY {proxy+}

custom:
  stage: ${opt:stage, self:provider.stage}

  wsgi:
    app: mapit.wsgi.application
